export const PROFESSION_DOMAINS = {
  CAREER_AND_JOB_SEARCH: "CAREER_AND_JOB_SEARCH",
  SOFTWARE_ENGINEERING: "SOFTWARE_ENGINEERING",
  PRODUCT_MANAGEMENT: "PRODUCT_MANAGEMENT",
  UI_UX_DESIGN: "UI_UX_DESIGN",
  DATA_SCIENCE_AND_AI: "DATA_SCIENCE_AND_AI",
  BUSINESS_AND_STARTUPS: "BUSINESS_AND_STARTUPS",
  FINANCE_AND_ACCOUNTING: "FINANCE_AND_ACCOUNTING",
  LEGAL_ADVICE: "LEGAL_ADVICE",
  DIGITAL_MARKETING: "DIGITAL_MARKETING",
  SALES_AND_BUSINESS_DEVELOPMENT: "SALES_AND_BUSINESS_DEVELOPMENT",
  HIGHER_EDUCATION_AND_ADMISSIONS: "HIGHER_EDUCATION_AND_ADMISSIONS",
  HEALTH_AND_WELLNESS: "HEALTH_AND_WELLNESS",
  LEADERSHIP_AND_MANAGEMENT: "LEADERSHIP_AND_MANAGEMENT",
  CONTENT_CREATION_AND_MEDIA: "CONTENT_CREATION_AND_MEDIA",
  HUMAN_RESOURCES_AND_RECRUITING: "HUMAN_RESOURCES_AND_RECRUITING",
  CYBERSECURITY: "CYBERSECURITY",
  DEVOPS_AND_CLOUD_COMPUTING: "DEVOPS_AND_CLOUD_COMPUTING",
  REAL_ESTATE_AND_INVESTING: "REAL_ESTATE_AND_INVESTING",
  PERSONAL_DEVELOPMENT_AND_LIFE_COACHING: "PERSONAL_DEVELOPMENT_AND_LIFE_COACHING",
  CREATIVE_ARTS_AND_WRITING: "CREATIVE_ARTS_AND_WRITING",
  OTHERS: "OTHERS",
} as const;

// TypeScript Type এক্সপোর্ট (যা Zod বা ইন্টারফেসে টাইপ হিসেবে ইউজ করতে পারবেন)
export type ProfessionDomain =
  (typeof PROFESSION_DOMAINS)[keyof typeof PROFESSION_DOMAINS];